version: "3.8"
services:

  backend:
    image: backend:randomname
    environment: 
      - SERVER_LISTEN_ADDRESS=8080

  frontend:
    image: frontend:randomname
    ports:
      - "8081:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    links:
      - backend
    